version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: todo_list_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo_list_db
      MYSQL_USER: lamdoanh
      MYSQL_PASSWORD: 123
    ports:
      - "3303:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d   
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - todo_net

volumes:
  mysql_data:

networks:
  todo_net:
    driver: bridge
